import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { useEffect, useState } from 'react';
import './globals.css'

import Sidebar from './components/Sidebar';
import HeaderBar from './components/HeaderBar';
import RobotList from './components/RobotList';
import { ecobot_status_temp } from '@prisma/client';


const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      {/* <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests" /> */}
      <body className='h-screen w-screen overflow-x-hidden'>
        {/* <body> */}
        {/* <HeaderBar /> */}
        <div className="flex h-full">
          <Sidebar />
          <RobotList />
          <main className='w-4/6 h-full'>{children}</main>
        </div>
      </body>
    </html >
  );
}
