"use client"

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { useEffect } from 'react';
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  useEffect(() => {
    const naverMapScript = document.createElement('script');
    naverMapScript.src = `https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=${process.env.NEXT_PUBLIC_NAVER_MAP_API_KEY}`;
    naverMapScript.onload = () => {
      if (window.naver && window.naver.maps) {
        console.log('Naver Map API loaded');
      }
    };
    document.head.appendChild(naverMapScript);
  }, []);

  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
