"use client"

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { useEffect, useState } from 'react';
import './globals.css'

import Sidebar from './components/Sidebar';
import HeaderBar from './components/HeaderBar';
import type { RobotStatus } from '.';
import RobotData from './components/RobotData';

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  useEffect(() => {
    const naverMapScript = document.createElement('script');
    naverMapScript.src = `https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=${process.env.NEXT_PUBLIC_NAVER_MAP_API_KEY}`;
    naverMapScript.onload = () => {
      if (window.naver && window.naver.maps) {
        console.log('Naver Map API loaded');
      }
    };
    document.head.appendChild(naverMapScript);
  }, []);

  const [robotStatus, setRobotStatus] = useState<RobotStatus[]>([]);

  const fetchData = async () => {
    const response = await fetch('/api/ecobot_status');
    const data = await response.json();
    setRobotStatus(data);
  };

  useEffect(() => {
    fetchData(); // 처음 로딩 시 데이터 가져오기

    const interval = setInterval(() => {
      fetchData();
    }, 10000);

    return () => clearInterval(interval); // 컴포넌트 언마운트 시 인터벌 정리
  }, []);

  return (
    <html lang="en">
      <body>
        <HeaderBar />
        <div className="flex overflow-x-hidden">
          <Sidebar />
          <RobotData robotStatus={robotStatus} />
          <main className='h-screen w-4/6'>{children}</main>
        </div>
      </body>
    </html>
  );
}
